---
- hosts: 'localhost'
  connection: local
  remote_user: user
  become_method: sudo
  tasks:
  - name: Insert const generateIndex
    lineinfile:
      path: node_modules/@antora/site-generator-default/lib/generate-site.js
      insertafter: 'use strict'
      line: "const generateIndex = require('antora-lunr')"

  - name: Insert const index
    lineinfile:
      path: node_modules/@antora/site-generator-default/lib/generate-site.js
      insertafter: 'const siteFiles = mapSit'
      line: "  const index = generateIndex(playbook, pages)"

  - name: Insert line siteFiles.push(generateIndex.createIndexFile(index))
    lineinfile:
      path: node_modules/@antora/site-generator-default/lib/generate-site.js
      insertafter: 'const index = generateIn'
      line: "  siteFiles.push(generateIndex.createIndexFile(index))"
...